# Generated by Django 3.0.8 on 2020-08-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='Shop_Image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='Shopname',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.TextField(max_length=20, null=True)),
                ('Price', models.TextField(max_length=5, null=True)),
                ('Quantity', models.TextField(max_length=4, null=True)),
                ('Product_Type', models.TextField(max_length=20, null=True)),
                ('Product_Image', models.FileField(null=True, upload_to='')),
                ('Product_Dis', models.TextField(max_length=50, null=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.ShopDetail')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
