# Generated by Django 3.0.8 on 2020-08-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200808_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
